### ISSUE TITLE
Should start in systray

### ISSUE THREAD

**Issue by Nama** [sas41/ProcessAffinityControlTool#1]
Since this tool is designed to run in the background, it would make much more sense if it wouldn't open the main window after the first start.

A command line parameter would also work ofc^^

**Comment by sas41** [comment]
Hey,
I must have missed this new issue in the chaos of the last couple of weeks, since it's trivial to implement, I took the liberty of getting it done as soon as I got some free time.

The following commit to main implements this feature: https://github.com/sas41/ProcessAffinityControlTool/commit/1021a74ec34976b70d76a70ed63d083a27e79264

The CLA, ``-start_minimized`` should now start the application minimized to the system tray.

Cheers!

P.S. I will push this feature to the Steam build of the application once it's been tested and no related issues are opened for a week or two.

**Comment by Nama** [comment]
Thank you. First tests are working correctly!

README.md has a typo.
> launched, minized
