### ISSUE TITLE
Ignore list is not working correctly

### ISSUE THREAD

**Issue by Nama** [sas41/ProcessAffinityControlTool#4]
Hi,

while testing for the other issues I wrote, I noticed that the ignore list only works for once as you move the process to the list.
As the process starts next time, it gets the configuration applied, which I set for normal processes. Even tho, all threads should be activated. I double-checked that with different processes.

Btw: Moving a process to the ignore list should enable all threads for this process.

Please look in to fixing this, thanks!

**Comment by sas41** [comment]
This will probably take precedent over adding new features, I feel bummed that I had email notifications disabled, I wish I had seen this issue raised when it was raised.

I will try to get on this next chance I get, thanks for being diligent and bringing it up!

**Comment by sas41** [comment]
Okay, so further testing revealed the cause of this issue.
It's the method by which a process is started.

So, if you have process in the Ignore List, it's affinity and priority are untouched by PACT.
However, if that processes was with a certain affinity and/or priority, then those will remain as such while the process is in the Ignore List.

For example, if I launch notepad, while it's in the ignore list, it will not be launched to work on all threads and normal priority like processes usually are, it will instead inherit the affinity but not the priority of the parent process.  In this case, the parent process will be explorer, so whatever explorer's affinity is, that's what notepad's affinity will be.

As far as I can tell, this is expected behavior, and the processes is actually ignored, unaltered.
To achieve a desired effect of having the process run as normal, we can set it to Custom Performance and give it all threads and a "Normal" priority.

I really don't think moving a process to the Ignore list should alter it's affinity or priority by default, as the Ignore list is meant to simply ignore and not alter anything about a process.

However, it's not all grim, a toggle can be added to make the Ignore List behave in the way you suggested, but that would be a new feature.

**Comment by Nama** [comment]
Oh that's how it is. Thank you!
